name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - uses: egor00f/install-kolibrios-toolchain-action@v1.1

    - name: kolibros repo
      run: cd .. && git clone https://github.com/KolibriOS/kolibrios.git

    - name: lua repo
      run: cd .. && git clone https://github.com/egor00f/lua-kolibrios.git

    - name: Build
      run: make build

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
          name: libini-build
          path: ./src/libini.dll
    
